[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.install]
cmds = ["mvn clean install -DskipTests"]

[phases.build]
cmds = ["mvn package -DskipTests"]

[start]
cmd = "java -jar target/premier-zone-0.0.1-SNAPSHOT.jar"
